---
# handlers file for web-stg

    - name: restart_httpd
      service:
        name: apache2
        state: restarted

    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted

